pull_request_rules:
  - name: backport to develop
    conditions:
      - label="backport develop"
    actions:
      backport:
        branches:
          - develop
        assignees:
          - "{{ author }}"

  - name: backport to version-16-beta
    conditions:
      - label="backport version-16-beta"
    actions:
      backport:
        branches:
          - version-16-beta
        assignees:
          - "{{ author }}"
